name: trigger jenkins job
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://master-jenkins-csb-distribution.apps.ocp4.prod.psi.redhat.com/view/ubipop"
        user: "dajain"
        token: ${{ secrets.TOKEN }}
        job: "ubipop-pulp-integration"
